# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./GitHubCiCd/GitHubCiCd.csproj --output ./sample-app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: github.event_name != 'pull_request'
      with:
        name: sample-app
        path: ./sample-app
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx
    - name: Generate test summary
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Tests
        path: GitHubCiCd.Tests/TestResults/*.trx
        reporter: dotnet-trx
